[package]
name = "rust_ex_3_solution"
version = "0.1.0"
authors = ["Timothy Bess <tdbgamer@gmail.com>"]
edition = "2018"

[dependencies]
csv = "1.0.5"
serde = { version = "1.0.87", features = ["derive"] }
